---
- name: "LSD | Install"
  community.general.pacman:
    name: lsd
    state: present
  become: true

- name: "LSD | Ensure lsd directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/lsd

- name: "LSD | Symlink lsd config"
  ansible.builtin.file:
    # src: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
    # src: config.yaml
    src: "{{ role_path }}/files/config.yaml"
    dest: ~/.config/lsd/config.yaml
    mode: "0644"
    state: link
    force: true

- name: "LSD | Symlink lsd colors"
  ansible.builtin.file:
    # src: colors.yaml
    src: "{{ role_path }}/files/colors.yaml"
    dest: ~/.config/lsd/colors.yaml
    mode: "0644"
    state: link
    force: true
