- name: "Alacritty | Install"
  community.general.pacman:
    name: alacritty
    state: present
  become: true

- name: "Alacritty | Ensure alacritty directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/alacritty

- name: "Alacritty | Symlink alacritty config"
  ansible.builtin.file:
    src: "{{ role_path }}/files/alacritty.toml"
    dest: ~/.config/alacritty/alacritty.toml
    mode: "0644"
    state: link
    force: true

- name: "Alacritty | Symlink alacritty keybinds"
  ansible.builtin.file:
    src: "{{ role_path }}/files/keybinds.toml"
    dest: ~/.config/alacritty/keybinds.toml
    mode: "0644"
    state: link
    force: true

- name: "Alacritty | Symlink alacritty theme catppuccin_mocha"
  ansible.builtin.file:
    src: "{{ role_path }}/files/catppuccin_mocha.toml"
    dest: ~/.config/alacritty/catppuccin_mocha.toml
    mode: "0644"
    state: link
    force: true

- name: "Alacritty | Symlink alacritty theme gruvbox_dark"
  ansible.builtin.file:
    src: "{{ role_path }}/files/gruvbox_dark.toml"
    dest: ~/.config/alacritty/gruvbox_dark.toml
    mode: "0644"
    state: link
    force: true

- name: "Alacritty | Symlink alacritty theme tokyo-night"
  ansible.builtin.file:
    src: "{{ role_path }}/files/tokyo-night.toml"
    dest: ~/.config/alacritty/tokyo-night.toml
    mode: "0644"
    state: link
    force: true
