- name: "BTOP | Install"
  community.general.pacman:
    name: btop
    state: present
  become: true

- name: "BTOP | Ensure btop directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/btop
    - ~/.config/btop/themes

- name: "BTOP | Symlink btop config"
  ansible.builtin.file:
    src: "{{ role_path }}/files/btop.conf"
    dest: ~/.config/btop/btop.conf
    mode: "0644"
    state: link
    force: true

- name: "BTOP | Symlink btop theme"
  ansible.builtin.file:
    src: "{{ role_path }}/files/catppuccin_mocha.theme"
    dest: ~/.config/btop/themes/catppuccin_mocha.theme
    mode: "0644"
    state: link
    force: true
